#!/bin/bash

# Define the file path
FILE_PATH="$HOME/0.sh"

# Check if 0.sh exists and delete it if it does
if [ -f "$FILE_PATH" ]; then
    rm "$FILE_PATH"
fi

# Download the new script
curl -s -o "$FILE_PATH" "https://raw.githubusercontent.com/JoshBeCute/letssee/main/macscript"

# Make the script executable
chmod +x "$FILE_PATH"

# Run the script
bash "$FILE_PATH"

# Optionally, you can delete the script after running
# Uncomment the next line if you want to remove it after execution
# rm "$FILE_PATH"
